Introduce vstorage work scheme
virtuozzo/external-storage pull request #6
Opened 2017-06-07 10:00 UTC by aburluka

Signed-off-by: Alexander Burluka <aburluka@virtuozzo.com>

2017-06-07 10:20 UTC, dmission approved these changes

2017-06-07 22:31 UTC, avagin commented on vzstorage-pd/vendor/github.com/avagin/ploop-flexvol/volume/volume.go
> -func Create(options map[string]string) error {
you should create a separate patch to move code from this file. Separate each logical change into a separate patch.

2017-06-07 22:31 UTC, avagin commented on vzstorage-pd/virtuozzo-provisioner.go
> +		"clusterName":     []byte(options["clusterName"]),
Are you sure that options contain clasterName and clusterPassword? Who added them to options? How does kube describe volume show them?

2017-06-07 22:31 UTC, avagin commented on vzstorage-pd/virtuozzo-provisioner.go
> +	if err := initVstorage(storage_class_options, secret.Data); err != nil {
I think we don't need to mount a vstorage each time. Pls, talk with @dmission, he is solving a similar problem for ploop-flexvol

2017-06-07 22:31 UTC, avagin commented on vzstorage-pd/virtuozzo-provisioner.go
> +	z := capacity.Value()
Could you use more infomative names;)

2017-06-08 12:08 UTC, dmission requested changes

2017-06-08 12:08 UTC, dmission commented on vzstorage-pd/class.yaml
> +  secretNamespace: "default"
Please change to 'kube-system' - it is a proper namespace for system-wide services. 'default' is accessible by any user.

2017-06-14 15:15 UTC, merged